export const WORKFLOW_ACTION_TYPES = {
  CLEANUP: "CLEANUP",
  UNSUBSCRIBE: "UNSUBSCRIBE",
};

export const WORKFLOW_EXECUTION_STATES = {
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
  MANUAL_ACTION_REQUIRED: "MANUAL_ACTION_REQUIRED",
  NOT_STARTED: "NOT_STARTED",
  PARTIAL_SUCCESS: "PARTIAL_SUCCESS",
  PAUSED: "PAUSED",
  REAUTH_REQUIRED: "REAUTH_REQUIRED",
  RUNNING: "RUNNING",
};

export const WORKFLOW_BLOCKING_REASONS = {
  LEASE_EXPIRED: "LEASE_EXPIRED",
  PAUSED: "PAUSED",
  USAGE_LIMIT_REACHED: "USAGE_LIMIT_REACHED",
};