export const CLEANUP_EXECUTION_RESULT_STATUSES = {
  ALREADY_COMPLETED: "ALREADY_COMPLETED",
  FAILED_PERMANENT: "FAILED_PERMANENT",
  FAILED_RETRYABLE: "FAILED_RETRYABLE",
  LEASE_EXPIRED: "LEASE_EXPIRED",
  PAUSED: "PAUSED",
  REAUTH_REQUIRED: "REAUTH_REQUIRED",
  SUCCESS: "SUCCESS",
};

export const CLEANUP_EXECUTION_GROUP_STATUSES = {
  ALL_SUCCEEDED: "ALL_SUCCEEDED",
  NONE_SUCCEEDED: "NONE_SUCCEEDED",
  PARTIAL_SUCCESS: "PARTIAL_SUCCESS",
};