export const SCAN_SOURCES = {
  ACTIVE_MAIL: "ACTIVE_MAIL",
  TRASH: "TRASH",
};

export const SCAN_STATES = {
  COMPLETE: "COMPLETE",
  DISCOVERING: "DISCOVERING",
  FAILED: "FAILED",
  PARTIAL_RESULTS_AVAILABLE: "PARTIAL_RESULTS_AVAILABLE",
  PAUSED: "PAUSED",
  REAUTH_REQUIRED: "REAUTH_REQUIRED",
  RESOURCE_LIMIT_REACHED: "RESOURCE_LIMIT_REACHED",
};

export const SCAN_RESOURCE_LIMIT_CODES = {
  MAX_RETAINED_MESSAGES: "MAX_RETAINED_MESSAGES",
};

export const SCAN_PAUSE_REASONS = {
  LEASE_EXPIRED: "LEASE_EXPIRED",
  USER_REQUESTED: "USER_REQUESTED",
};

export const SCAN_SOURCE_QUERIES = {
  [SCAN_SOURCES.ACTIVE_MAIL]: "-in:trash -in:spam",
  [SCAN_SOURCES.TRASH]: "in:trash",
};

export const DEFAULT_SCAN_METADATA_HEADERS = [
  "From",
  "To",
  "Subject",
  "Date",
  "List-Unsubscribe",
  "List-Unsubscribe-Post",
  "List-ID",
  "Precedence",
  "Reply-To",
  "Sender",
];

export const SOURCE_SCAN_ORDER = [SCAN_SOURCES.ACTIVE_MAIL, SCAN_SOURCES.TRASH];