export const UNSUBSCRIBE_OPERATION_TYPES = {
  HTTP_LINK: "HTTP_LINK",
  HTTPS_LINK: "HTTPS_LINK",
  MAILTO: "MAILTO",
  RFC8058_ONE_CLICK: "RFC8058_ONE_CLICK",
  UNSAFE_URL: "UNSAFE_URL",
};

export const UNSUBSCRIBE_OPERATION_STATUSES = {
  AUTOMATIC: "AUTOMATIC",
  MANUAL_ACTION_REQUIRED: "MANUAL_ACTION_REQUIRED",
  UNAVAILABLE: "UNAVAILABLE",
  UNSAFE: "UNSAFE",
};

export const RFC8058_ONE_CLICK_TOKEN = "list-unsubscribe=one-click";