export const UNSUBSCRIBE_OPERATION_TYPES = {
  HTTP_LINK: "HTTP_LINK",
  HTTPS_LINK: "HTTPS_LINK",
  MAILTO: "MAILTO",
  RFC8058_ONE_CLICK: "RFC8058_ONE_CLICK",
  UNSAFE_URL: "UNSAFE_URL",
};

export const UNSUBSCRIBE_OPERATION_STATUSES = {
  AUTOMATIC: "AUTOMATIC",
  MANUAL_ACTION_REQUIRED: "MANUAL_ACTION_REQUIRED",
  UNAVAILABLE: "UNAVAILABLE",
  UNSAFE: "UNSAFE",
};

export const UNSUBSCRIBE_EXECUTION_RESULT_STATUSES = {
  ALREADY_COMPLETED: "ALREADY_COMPLETED",
  FAILED_PERMANENT: "FAILED_PERMANENT",
  FAILED_RETRYABLE: "FAILED_RETRYABLE",
  LEASE_EXPIRED: "LEASE_EXPIRED",
  MANUAL_ACTION_REQUIRED: "MANUAL_ACTION_REQUIRED",
  PAUSED: "PAUSED",
  SUCCESS: "SUCCESS",
  UNSAFE_TARGET: "UNSAFE_TARGET",
  USAGE_LIMIT_REACHED: "USAGE_LIMIT_REACHED",
};

export const UNSUBSCRIBE_EXECUTION_GROUP_STATUSES = {
  ALL_SUCCEEDED: "ALL_SUCCEEDED",
  MANUAL_ACTION_REQUIRED: "MANUAL_ACTION_REQUIRED",
  NONE_SUCCEEDED: "NONE_SUCCEEDED",
  PARTIAL_SUCCESS: "PARTIAL_SUCCESS",
};

export const UNSUBSCRIBE_EXECUTION_SUPPORTED_PORTS = new Set(["", "443"]);

export const RFC8058_ONE_CLICK_TOKEN = "list-unsubscribe=one-click";

export const UNSUBSCRIBE_FAILURE_CATEGORIES = {
  CONNECTION_FAILURE: "CONNECTION_FAILURE",
  DNS_FAILURE: "DNS_FAILURE",
  HTTP_4XX: "HTTP_4XX",
  HTTP_5XX: "HTTP_5XX",
  INVALID_RESPONSE: "INVALID_RESPONSE",
  REDIRECT_REJECTED: "REDIRECT_REJECTED",
  SECURITY_REJECTED: "SECURITY_REJECTED",
  TIMEOUT: "TIMEOUT",
  TLS_FAILURE: "TLS_FAILURE",
  UNKNOWN: "UNKNOWN",
  UNSUPPORTED_RESPONSE: "UNSUPPORTED_RESPONSE",
};

export const UNSUBSCRIBE_DLQ_MAX_ENTRIES = 200;
export const UNSUBSCRIBE_DLQ_BODY_EXCERPT_LIMIT = 256;