export const SENDER_CATEGORIES = {
  NEWSLETTER: "NEWSLETTER",
  NOTIFICATION: "NOTIFICATION",
  PROMOTIONAL: "PROMOTIONAL",
  SOCIAL: "SOCIAL",
  TRANSACTIONAL: "TRANSACTIONAL",
  UNKNOWN: "UNKNOWN",
  UPDATES: "UPDATES",
};

export const ATTENTION_LEVELS = {
  HIGH: "HIGH",
  LOW: "LOW",
  MEDIUM: "MEDIUM",
};

export const SIGNAL_STRENGTHS = {
  STRONG: "STRONG",
  SUPPORTING: "SUPPORTING",
};

export const CATEGORY_PRECEDENCE = [
  SENDER_CATEGORIES.TRANSACTIONAL,
  SENDER_CATEGORIES.SOCIAL,
  SENDER_CATEGORIES.NOTIFICATION,
  SENDER_CATEGORIES.NEWSLETTER,
  SENDER_CATEGORIES.PROMOTIONAL,
  SENDER_CATEGORIES.UPDATES,
  SENDER_CATEGORIES.UNKNOWN,
];

export const CLASSIFICATION_THRESHOLDS = {
  ATTENTION_HIGH_MESSAGE_COUNT: 25,
  ATTENTION_HIGH_TRASH_RATIO: 0.5,
  ATTENTION_HIGH_UNREAD_RATIO: 0.75,
  ATTENTION_MEDIUM_MESSAGE_COUNT: 10,
  ATTENTION_MEDIUM_TRASH_RATIO: 0.25,
  ATTENTION_MEDIUM_UNREAD_RATIO: 0.5,
  HEADER_RATIO_SUPPORTING: 0.4,
  LIST_HEADER_RATIO_STRONG: 0.6,
  MIN_CATEGORY_SCORE: 3,
  RECURRING_MESSAGE_COUNT: 3,
};